name: Update Version

on:
  push:
    branches:
    - main

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Allow untrusted commands (less secure)
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release version
        run: echo "::set-env name=NEW_VERSION::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"

      - name: Update version in code
        run: |
          sed -i "s/v0.0.1/${{ env.NEW_VERSION }}/" /version.md
          git add version.md
          git commit -m "Update version in code to ${{ env.NEW_VERSION }}" || true
          git push
