name: Update Version

on:
  release:
    types:
      - created

jobs:
  update_version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release version
        run: echo "::set-env name=NEW_VERSION::$(curl -s https://api.github.com/repos/${{ github.repository }}/releases/latest | jq -r .tag_name)"

      - name: Update version in code
        run: |
          sed -i "s/v0.0.1/${{ env.NEW_VERSION }}/" path/to/your/code
          git add path/to/your/code
          git commit -m "Update version in code to ${{ env.NEW_VERSION }}" || true
          git push
