name: Versioning Cheker

on:
    release: 
        types:
            - created


jobs:
    update_version:
        runs-on: ubuntu-latest

        steps:
            - name: Versioning Checker
              uses: empathictech/versioning-checker@2.1.6
              with:
                tracked_files: 'APP_VERSION,CHANGELOG.md'
                version_regex:  '[0-9]+\.[0-9]+\.[0-9]+'
                fork_repo_name: 'mwcodebase/versioning-checker'
        